development: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRES_ENV_POSTGRES_DATABASE'] %>
  username: <%= ENV['POSTGRES_ENV_POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_ENV_POSTGRES_PASSWORD'] %>
  host: postgres
  pool: 5

test:
  <<: *default
  database: myapp_test