development: &default
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  username: postgres
  password: postgres
  host: postgres
  pool: 5

test:
  <<: *default
  database: myapp_test