web:
  image: rails:4.2
  command: "bundle exec rails server -p 3000"
  ports:
   - "3000:3000"
  links:
   - redis
   - postgres

redis:
  image: redis:3.0

postgres:
  image: postgres:9.4
  environment:
    POSTGRES_DATABASE: test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_ROOT_PASSWORD: supersecret
